### ISSUE TITLE
Request SecuredCaptureRequest{model: PaymentDetails} is not supported.

### ISSUE THREAD

**Issue by a2xchip** [a2xchip/SagepayBundleSandbox#1]
While executing Payum:Capture:do 

```
 $payment->execute(new SecuredCaptureRequest($token)); 
// throws request not supported exception. 
```

**Comment by a2xchip** [comment]
@makasim Please! May you help me? What am I doing wrong here? in implementation of new payment bundle. 
I thought that it is something related to sylius but using sandbox app realize that it is not.

**Comment by makasim** [comment]
what version do you use? SecuredCaptureRequest - there is not such request atm...

**Comment by makasim** [comment]
I found, there is not any actions are able to execute your request. And if you look at your capture supports method: https://github.com/LedjIn/Sagepay/blob/master/Action/CaptureOnsiteAction.php#L93

You will see that it requires Capture request (from 0.12 version) but in the sandbox you installed Payum 0.9 version. try to sync them

**Comment by makasim** [comment]
Looks strange: https://github.com/LedjIn/Sagepay/blob/master/Action/CaptureOnsiteAction.php#L93. Is it something custom? or? There is not such code in Payum

**Comment by makasim** [comment]
You can put the symfony [payment factory](https://github.com/a2xchip/SagepayBundleSandbox/blob/0acf41291e00e0d998a10d81d0d0834fa2e3c8b1/src/Ledjin/Bundle/SagepayBundle/DependencyInjection/Factory/Payment/SagepayOnsitePaymentFactory.php#L14) to the lib itself like it was done here: https://github.com/locastic/TcomPayWayPayum/tree/master/src/Locastic/TcomPayWayPayum/Bridge/Symfony

**Comment by makasim** [comment]
It is better to move logic from https://github.com/a2xchip/SagepayBundleSandbox/blob/master/src/Ledjin/Bundle/SagepayBundle/Payum/Sagepay/Action/CapturePaymentUsingSagepayOnsiteAction.php to FillOrderDetailsAction ([like this one](https://github.com/Payum/Payum/blob/master/src/Payum/Be2Bill/Action/FillOrderDetailsAction.php)). And move it to the lib itself.

**Comment by makasim** [comment]
And it would be better if you open a PR and ping me there so I can review it.

**Comment by a2xchip** [comment]
@makasim Oops.. so it is may be because of version incompatibility... I started implementation using 0.12 version and than found that sylius uses 0.9 and first of all i need sylius integration of this gateway. 
Maksim thank you very much for such fast reply to the question. I'll try to refactor code according to 0.9 version requests. Thanks again!

**Comment by a2xchip** [comment]
@makasim What do you mean saing "open PR"?

**Comment by makasim** [comment]
>  found that sylius uses 0.9

Sylius 0.12  (current dev) supports Payum 0.12.

**Comment by makasim** [comment]
you can open a pull request here in this repository or in the library and send me the link or ping me in the comment. It is much easier to review the code in the pull request.

**Comment by makasim** [comment]
>  I'll try to refactor code according to 0.9 version requests. Thanks again!

It would be better to stick with 0.12, 0.9 is not supported any more, even in sylius

**Comment by a2xchip** [comment]
@makasim the version of my production sylius is 0.11 but during test of sagepaybundle i use 0.12-dev and in composer.json i see 

```
"payum/payum":                          "~0.9.0",
"payum/payum-bundle":                   "~0.9.0",
```

but 
`"sylius/payum-bundle": "0.12.x-dev",`

i use the development version 
created by `create-project sylius/sylius -s dev`

**Comment by makasim** [comment]
the sylius 0.12 was released last week, I believe

**Comment by a2xchip** [comment]
@makasim Yes. 

Is there any difference in third party bundle's payment factory creation using payment.xml or via explicit method and service registration? 
`app/console cont:debug|grep sagepay` gives me 

```
payum.context.sagepay_onsite.api                                                 container Ledjin\Sagepay\Api                                                                         
payum.context.sagepay_onsite.payment                                             container Payum\Core\Payment   
```

And I thought that there is no problem?

**Comment by makasim** [comment]
> Is there any difference in third party bundle's payment factory creation using payment.xml or via explicit method and service registration? 

could you please give more details. I do not understand.

**Comment by a2xchip** [comment]
@makasim Between this https://github.com/a2xchip/SagepayBundleSandbox/blob/master/src/Ledjin/Bundle/SagepayBundle/Payum/Sagepay/Action/CapturePaymentUsingSagepayOnsiteAction.php
and this 
https://github.com/locastic/TcomPayWayPayum/blob/master/src/Locastic/TcomPayWayPayum/Bridge/Symfony/TcomPayWayPaymentFactory.php
methods

**Comment by makasim** [comment]
They are completely different things first is an action of the payment and the second one a factory that creates the whole payment (with actions insde it). Still dont get the question, sorry.

**Comment by a2xchip** [comment]
@makasim Ooops misspelling i mean this 
https://github.com/a2xchip/SagepayBundleSandbox/blob/master/src/Ledjin/Bundle/SagepayBundle/DependencyInjection/Factory/Payment/SagepayOnsitePaymentFactory.php

and this method of factory creation
https://github.com/locastic/TcomPayWayPayum/blob/master/src/Locastic/TcomPayWayPayum/Bridge/Symfony/TcomPayWayPaymentFactory.php

**Comment by makasim** [comment]
yes, it looks good. Just in case you dont know how to register it, here's an example: https://github.com/Payum/PayumBundle/blob/master/PayumBundle.php#L35

**Comment by a2xchip** [comment]
@makasim Yes, I register it in bundles class build method. Thank you very much! It is clear now! :+1:
